image: "golang:1.13"

before_script:
  - mkdir -p /go/src/github.com/katzenpost
  - cp -r /builds/katzenpost/* /go/src/github.com/katzenpost/
  - cd /go/src/github.com/katzenpost/mailproxy

test-mailproxy:
  script:
    - go test -v -cover -race ./...
